---
development:
  cloud_name: <%= ENV['CALENDLY_CLOUD_NAME'] %>
  api_key: <%= ENV['CALENDLY_API_KEY'] %>
  api_secret: <%= ENV['CALENDLY_API_SECRET'] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= ENV['CALENDLY_CLOUD_NAME'] %>
  api_key: <%= ENV['CALENDLY_API_KEY'] %>
  api_secret: <%= ENV['CALENDLY_API_SECRET'] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: <%= ENV['CALENDLY_CLOUD_NAME'] %>
  api_key: <%= ENV['CALENDLY_API_KEY'] %>
  api_secret: <%= ENV['CALENDLY_API_SECRET'] %>
  enhance_image_tag: true
  static_file_support: false
